services:
  postgres:
    image: postgres:16
    container_name: cloudforge-postgres

    environment:
      POSTGRES_DB: cloudforge
      POSTGRES_USER: cloudforge
      POSTGRES_PASSWORD: cloudforge

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    image: cloudforge/user-service:1.0
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloudforge
      SPRING_DATASOURCE_USERNAME: cloudforge
      SPRING_DATASOURCE_PASSWORD: cloudforge
volumes:
  postgres_data:
