services:
  postgres:
    image: postgres:16
    container_name: cloudforge-postgres

    environment:
      POSTGRES_DB: cloudforge
      POSTGRES_USER: cloudforge
      POSTGRES_PASSWORD: cloudforge

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
