userService:
  replicaCount: 3

  image:
    repository: 761558631184.dkr.ecr.us-east-1.amazonaws.com/user-service
    tag: "eb932a44a0d33f1216c4de1423ad04ad9b3ac07a"
    pullPolicy: IfNotPresent

  containerPort: 8080

  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
