userService:
  replicaCount: 3

  image:
    repository: 761558631184.dkr.ecr.us-east-1.amazonaws.com/user-service
    tag: "fc68c82cb3ed385cf85412319dde07880f701c3b"
    pullPolicy: IfNotPresent

  containerPort: 8080

  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
